### ISSUE TITLE
“147971为空跳过“一直显示这个，貌似不行耶

### ISSUE THREAD

**Issue by boytoto** [rekols/cqooc#3]
![QQ截图20200426202336](https://user-images.githubusercontent.com/52145626/80307549-4e192300-87fc-11ea-9e39-9b01255350de.png)

**Comment by rekols** [comment]
有空我看看

**Comment by rekols** [comment]
https://github.com/rekols/cqooc/commit/803fc35b2d6cc31ea6ec1bf98bc3652a83af06a3 

已经修复
